version: '3'
services:
    jupyter:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        environment: 
            - PYTHONPATH=/home/jovyan/work/src
        ports:
            - "{{cookiecutter.jupyter_port}}:{{cookiecutter.jupyter_port}}"
        volumes:
            - .:/home/jovyan/work:cached
