version: '3'
services:
    jupyter:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        ports:
            - "{{cookiecutter.jupyter_port}}:{{cookiecutter.jupyter_port}}"
        volumes:
            - .:/home/jovyan/work:cached
