version: '3'
services:
    python:
        build:
            context: ./Docker/
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - ./work:/home/jovyan/work
