version: '3'
services:
    jupyter:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        user: root
        env_file:
            - custom.env
        environment: 
            - DATAVOLUME=/home/jovyan/data-volume
        ports:
            - "{{cookiecutter.host_port}}:{{cookiecutter.container_port}}"
        volumes:
            - .:/home/jovyan/work:cached
            - {{cookiecutter.volume_name}}:/home/jovyan/data-volume

volumes:
    {{cookiecutter.volume_name}}: